### ISSUE TITLE
Bike Now: New Error - Textures with dimensions16x256 are larger than  the maximum supported size 0x0

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/BikeNow#4]
Error was reported on 2/14/2015 4:18:26 AM, exception type: Xamarin.InsightsCore.AndroidException, message: Textures with dimensions16x256 are larger than  the maximum supported size 0x0, details at https://insights.xamarin.com/app/9eda44e42d83722b25fb9809ac55b2366f6e8626/issues/454915f4706a86a67b38263c2ef55652cd7d2042

**Comment by pankon** [comment]
Hi James, I came across a similar bug - how did you solve this issue? Thanks

**Comment by AdamoPrincipe** [comment]
I have the same bug.
Anyone solved this?
